version: '3.8'

services:
  mikaleb_front:
    restart: unless-stopped
    image: mikaleb_front
    container_name: mikaleb_front
    entrypoint: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    volumes:
      - '.:/app'
      - /app/node_modules/
    labels:
      - traefik.enable=true
      - traefik.http.routers.mikaleb_front.tls=true
      - traefik.http.routers.mikaleb_front.tls.certresolver=lets-encrypt
      - traefik.http.routers.mikaleb_front.rule=Host(`mikaleb.com`)
      - traefik.http.routers.mikaleb_front.entrypoints=websecure
      - traefik.port=3000
    env_file:
      - .env
    networks:
      - internal
      - web

networks:
  web:
    external: true
  internal:
    external: false
