version: '3.8'

services:
  app:
    restart: always
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=lets-encrypt
      - traefik.port=5173
      - traefik.http.routers.app.rule=Host(`mikaleb.com`)
      - traefik.http.routers.app.entrypoints=websecure
    env_file:
      - .env
    networks:
      - internal
      - web

networks:
  web:
    external: true
  internal:
    external: false
